### PR TITLE
search is now ordered based on release year

### PR DESCRIPTION
**Pull request by Catta1997**
I successfully did what I wanted, now the search is sorted by release year. 

Maybe it can be brought to other sources that do not do it by default, it would be more "tidy", maybe using MAL because not all sources indicate in the search results the year of release. or more simply order only the result of the sources that indicate it (for example animeultima and 4anime)

### CODE REVIEW

**Comment by uttiya10** [comment]
One possible problem with using MAL to get year of release, is that it will increase searching times, because you have to send a request to MAL for every anime. However, ordering websites such as 4anime and animeultima, which already provide dates, is not bad idea.

**Comment by Catta1997** [comment]
> One possible problem with using MAL to get year of release, is that it will increase searching times, because you have to send a request to MAL for every anime. However, ordering websites such as 4anime and animeultima, which already provide dates, is not bad idea.

ok, i have successfully added it even in "animeultima"

**Comment by uttiya10** [comment]
Both your commits have similar name, which can cause confusion. Can you amend your commit messages to include the `source name`?

**Comment by Catta1997** [comment]
> Edit: I actually dont know if its possible to rename commits in a pull request, so dont worry about it.
> 
> Both your commits have similar name, which can cause confusion. Can you amend your commit messages to include the `source name`?

the first is for `AnimeUnity`, the second for `AnimeUltima`

**Comment by SuperMarcus** [comment]
> Edit: I actually dont know if its possible to rename commits in a pull request

It should be possible. Just force push to your branch and that should update the PR. Although there might be some unexpected glitches.

The question is, why are you trying to sort search results based on release years? Or am I missing something? Imo search results should always base on relativity instead of other attributes.

**Comment by uttiya10** [comment]
> My question is, why are you trying to sort search results based on release years? 

I was thinking the same thing at first
> I successfully did what I wanted, now the search is sorted by release year

However, this made me think that you guys were implementing a way to sort search results or something.

**Comment by Catta1997** [comment]
Just because some anime have multiple seasons and the results aren't sorted, so you can't know the order (some anime seasons don't indicate the number, they just change the name) and the movies aren't sorted either

**Comment by SuperMarcus** [comment]
> Just because some anime have multiple seasons and the results aren't sorted

Can you give me an example? Ideally we still want the search results in the app to match the order of the original website.

**Comment by Catta1997** [comment]
> > Just because some anime have multiple seasons and the results aren't sorted
> 
> Can you give me an example? Ideally, we still want the search results in the app to match the order of the original website.
> 
> Sorting the search results based on release years seems a little arbitrary. Is there a reason for this?

yes and no, in my opinion it would be more tidy but since some sources do not provide a year of release it would be only for some sources. For example Detective Conan and Naruto have several films and in most sources they are not ordered, so I thought about checking the year in order to order them correctly.
 But it’s not a problem if this “feature” will not added

**Pull request closed without merging**
