### PR TITLE
Added TheWatchCartoonOnline source

### PR DESCRIPTION
**Pull request by Catta1997**
The only part missing is the player (*+Epiode) . The problem is that the site think that I'm using an ad-blocker and there isn't the player int the source of the page

### CODE REVIEW

**Comment by Catta1997** [comment]
Source request on #132 issue

**Comment by SuperMarcus** [comment]
Thanks for submitting the PR! I didn't merge this yesterday because we were making some changes to the networking APIs in the `BaseSource`. Can you please update the PR and use the new APIs instead.

**Comment by Catta1997** [comment]
> Thanks for submitting the PR! I didn't merge this yesterday because we were making some changes to the networking APIs in the `BaseSource`. Can you please update the PR and use the new `RequestManager` APIs instead.

ok, also I see that AnimeUnity no longer work with this modifications so I will firstly resolve that

**Comment by SuperMarcus** [comment]
@Catta1997 any updates on this?

**Comment by Catta1997** [comment]
I’m away from home without a computer, I update it as soon as possible

**Comment by Catta1997** [comment]
@SuperMarcus done. But I can't add the file in this PR because I had to delete and recreate the fork because some files gave me error updating it. I will create another updated pr and close this

**Comment by SuperMarcus** [comment]
Closing in favor of #144

**Pull request closed without merging**
